server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/database?user=root=true&serverTimezone=UTC&useSSL=true&verifyServerCertificate=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    baseline-on-migrate: true