server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/database?user=root=true&serverTimezone=UTC&useSSL=true&verifyServerCertificate=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000
#logging:
#  level:
#    org.springframework.web: INFO
#    org.springframework.security: DEBUG
#    com.example: DEBUG
#  file: app.log

---

spring:
  profiles: e2e
  datasource:
    url: jdbc:h2:mem:messages;MODE=MySQL
    driver-class-name: org.h2.Driver
  jpa:
    database: mysql
  flyway:
    enabled: true